---
title: "Answer for Session3: Correlation and Linear Regression"
author: "MRC Clinical Sciences Centre (http://mrccsc.github.io/)"
date: "12/July/2016"
output: html_document
---

These exercises cover the sections of Statistics in R [Session3: Correlation and Linear Regression]("../Session3_linear_regression.html").

**Exercise 1**

- Read in the file lmExercise.txt.
```{r,message=T}
 lmExercise <- read.delim("../data/lmExercise.txt")
```

- What is the formula for the best fit lines for X vs Y and X vs Z
```{r,message=T}
 lmXY <- lm(x~y,lmExercise)
 lmXZ <- lm(x~z,lmExercise)
lmXY
 plot(x~y,lmExercise)
 abline(lmXY,col="red")
lmXZ
plot(x~z,lmExercise)
 abline(lmXZ,col="red")
```

- What are the Rsquared for X vs Y and X vs Z.
```{r,message=T}
str(summary(lmXY))
summary(lmXY)$r.squared
summary(lmXZ)$r.squared
```

- Predict values for X when Y is 100 and when Z is 100
```{r,message=T}
str(lmXY)
predictedXfromY <- unname(lmXY$coefficients[1] + lmXY$coefficients[2]*100)
predictedXfromZ <- unname(lmXZ$coefficients[1] + lmXZ$coefficients[2]*100)
predictedXfromY
predictedXfromZ
```

